# Change these first
owner: djvaughn # Your GitHub organization or username, where this repository lives
repo: VedaServer # The name of this repository

sites:
  - name: Plex Server
    url: $PLEX_URL/identity
    __dangerous__insecure: true
    icon: https://app.plex.tv/desktop/favicon.ico
    
assignees: # Users to assign downtime issues (optional)
  - djvaughn

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: VedaServer
  logoUrl: https://seeklogo.com/images/G/gundam-00-celestial-being-logo-E6E4232905-seeklogo.com.png
  name: "Veda Server Status"
  introTitle: Veda Server Status
  theme: dark
  publish: true
i18n:
  footer: ""
robotsText: "User-agent: * \n Disallow: /"
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/15 * * * *"
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
